# Generated by Django 5.2.5 on 2026-09-04 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='carona',
            name='destino',
            field=models.CharField(default='Muzambinho', max_length=99, verbose_name='Destino da Carona'),
        ),
        migrations.AddField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caronas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
        ),
    ]
