# Generated by Django 5.2.5 on 2026-09-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_carona_destino_carona_motorista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carona',
            name='destino',
        ),
    ]
