# Generated by Django 5.2.5 on 2026-09-11 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_cidade_options_cidade_is_verificado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cidade',
            options={'verbose_name': 'Cidade', 'verbose_name_plural': 'Cidades'},
        ),
        migrations.AlterModelOptions(
            name='perfilusuario',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.RemoveField(
            model_name='cidade',
            name='is_verificado',
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='is_verificado',
            field=models.BooleanField(default=False, help_text='Indica se a conta do usuário foi verificada no sistema.', verbose_name='Verificado'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
