# Generated by Django 5.2.5 on 2026-09-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cidade_options_alter_perfilusuario_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Nota da Avaliação'),
        ),
    ]
