# Generated by Django 5.2.5 on 2026-10-02 12:36

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_conversa_mensagem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
        migrations.AlterField(
            model_name='carona',
            name='destino',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='caronas_destino', to='app.cidade', verbose_name='Destino'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='carona',
            options={'ordering': ['data_hora'], 'verbose_name': 'Carona', 'verbose_name_plural': 'Caronas'},
        ),
        migrations.AlterModelOptions(
            name='conversa',
            options={'verbose_name': 'Conversa', 'verbose_name_plural': 'Conversas'},
        ),
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ['enviado_em'], 'verbose_name': 'Mensagem', 'verbose_name_plural': 'Mensagens'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'País', 'verbose_name_plural': 'Países'},
        ),
        migrations.RenameField(
            model_name='carona',
            old_name='dataHora',
            new_name='data_hora',
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='avaliador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_feitas', to=settings.AUTH_USER_MODEL, verbose_name='Avaliador'),
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='comentario',
            field=models.TextField(blank=True, max_length=500, verbose_name='Comentário'),
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='motorista',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista Avaliado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avaliacao',
            name='nota',
            field=models.DecimalField(decimal_places=1, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Nota da Avaliação'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='motorista',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='caronas', to=settings.AUTH_USER_MODEL, verbose_name='Motorista'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carona',
            name='origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caronas_origem', to='app.cidade', verbose_name='Origem'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='vagas',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Vagas Disponíveis'),
        ),
        migrations.AlterField(
            model_name='carona',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Valor da Carona'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='carona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversas', to='app.carona', verbose_name='Carona Associada'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='criado_em',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='conversa',
            name='participantes',
            field=models.ManyToManyField(related_name='conversas', to=settings.AUTH_USER_MODEL, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do Estado'),
        ),
        migrations.AlterField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pais', verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='conversa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='app.conversa', verbose_name='Conversa'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='enviado_em',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Enviado em'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='remetente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Remetente'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(verbose_name='Texto da Mensagem'),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome do País'),
        ),
        migrations.DeleteModel(
            name='Destino',
        ),
    ]
