# Generated by Django 5.2.5 on 2026-10-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_delete_chat_alter_carona_destino_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='lida',
            field=models.BooleanField(default=False, verbose_name='Lida'),
        ),
    ]
