# Generated by Django 5.2.5 on 2026-10-02 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_mensagem_lida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversa',
            options={'ordering': ['-criado_em'], 'verbose_name': 'Conversa', 'verbose_name_plural': 'Conversas'},
        ),
    ]
