# Generated by Django 5.2.5 on 2026-10-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_destino_alter_carona_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='PontosIF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Ponto')),
            ],
            options={
                'verbose_name': 'Ponto do IF',
                'verbose_name_plural': 'Pontos do IF',
                'ordering': ['nome'],
            },
        ),
    ]
