# Generated by Django 5.2.5 on 2026-10-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_pontosif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PontosIF',
        ),
    ]
