# Generated by Django 5.2.5 on 2026-10-09 12:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_solicitacaocnh'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitacaoCarona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aceita', 'Aceita'), ('recusada', 'Recusada'), ('cancelada', 'Cancelada')], default='pendente', max_length=15, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('respondido_em', models.DateTimeField(blank=True, null=True, verbose_name='Respondido em')),
                ('carona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='app.carona', verbose_name='Carona')),
                ('conversa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='app.conversa', verbose_name='Conversa')),
                ('passageiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes_carona', to=settings.AUTH_USER_MODEL, verbose_name='Passageiro')),
            ],
            options={
                'verbose_name': 'Solicitação de Carona',
                'verbose_name_plural': 'Solicitações de Carona',
                'ordering': ['-criado_em'],
            },
        ),
    ]
